spring:
  application:
    name: BeesCaatinga
  datasource:
    url: jdbc:postgresql://localhost:5432/beescaatinga-db
    username: postgres
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: dd/MM/yyyy
  jackson:
    date-format: dd/MM/yyyy
    time-zone: America/Sao_Paulo